//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AScript.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class AScriptBaseListener : IAScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] AScriptParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] AScriptParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] AScriptParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] AScriptParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] AScriptParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] AScriptParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strfield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrfield([NotNull] AScriptParser.StrfieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strfield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrfield([NotNull] AScriptParser.StrfieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrvalue([NotNull] AScriptParser.StrvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrvalue([NotNull] AScriptParser.StrvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strreplacevalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrreplacevalue([NotNull] AScriptParser.StrreplacevalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strreplacevalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrreplacevalue([NotNull] AScriptParser.StrreplacevalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDr([NotNull] AScriptParser.DrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDr([NotNull] AScriptParser.DrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.ns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNs([NotNull] AScriptParser.NsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.ns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNs([NotNull] AScriptParser.NsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.nsp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNsp([NotNull] AScriptParser.NspContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.nsp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNsp([NotNull] AScriptParser.NspContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.imptext"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImptext([NotNull] AScriptParser.ImptextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.imptext"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImptext([NotNull] AScriptParser.ImptextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.imp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImp([NotNull] AScriptParser.ImpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.imp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImp([NotNull] AScriptParser.ImpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.nullreplace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullreplace([NotNull] AScriptParser.NullreplaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.nullreplace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullreplace([NotNull] AScriptParser.NullreplaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringreplace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringreplace([NotNull] AScriptParser.StringreplaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringreplace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringreplace([NotNull] AScriptParser.StringreplaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.nadrop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNadrop([NotNull] AScriptParser.NadropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.nadrop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNadrop([NotNull] AScriptParser.NadropContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData([NotNull] AScriptParser.DataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData([NotNull] AScriptParser.DataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dataformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataformat([NotNull] AScriptParser.DataformatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dataformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataformat([NotNull] AScriptParser.DataformatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.comparedate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparedate([NotNull] AScriptParser.ComparedateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.comparedate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparedate([NotNull] AScriptParser.ComparedateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.adddate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdddate([NotNull] AScriptParser.AdddateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.adddate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdddate([NotNull] AScriptParser.AdddateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.datediff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatediff([NotNull] AScriptParser.DatediffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.datediff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatediff([NotNull] AScriptParser.DatediffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.monthadd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMonthadd([NotNull] AScriptParser.MonthaddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.monthadd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMonthadd([NotNull] AScriptParser.MonthaddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.monthbetween"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMonthbetween([NotNull] AScriptParser.MonthbetweenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.monthbetween"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMonthbetween([NotNull] AScriptParser.MonthbetweenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.next"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNext([NotNull] AScriptParser.NextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.next"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNext([NotNull] AScriptParser.NextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.formatingstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormatingstring([NotNull] AScriptParser.FormatingstringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.formatingstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormatingstring([NotNull] AScriptParser.FormatingstringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.todate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTodate([NotNull] AScriptParser.TodateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.todate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTodate([NotNull] AScriptParser.TodateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.totime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTotime([NotNull] AScriptParser.TotimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.totime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTotime([NotNull] AScriptParser.TotimeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dateformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDateformat([NotNull] AScriptParser.DateformatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dateformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDateformat([NotNull] AScriptParser.DateformatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.datefunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatefunction([NotNull] AScriptParser.DatefunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.datefunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatefunction([NotNull] AScriptParser.DatefunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dateadvancefunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDateadvancefunction([NotNull] AScriptParser.DateadvancefunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dateadvancefunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDateadvancefunction([NotNull] AScriptParser.DateadvancefunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringfunction([NotNull] AScriptParser.StringfunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringfunction([NotNull] AScriptParser.StringfunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringformat([NotNull] AScriptParser.StringformatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringformat([NotNull] AScriptParser.StringformatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.numberfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberfunction([NotNull] AScriptParser.NumberfunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.numberfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberfunction([NotNull] AScriptParser.NumberfunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.numberformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberformat([NotNull] AScriptParser.NumberformatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.numberformat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberformat([NotNull] AScriptParser.NumberformatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrings([NotNull] AScriptParser.StringsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrings([NotNull] AScriptParser.StringsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringltr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringltr([NotNull] AScriptParser.StringltrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringltr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringltr([NotNull] AScriptParser.StringltrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields([NotNull] AScriptParser.FieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields([NotNull] AScriptParser.FieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.sel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel([NotNull] AScriptParser.SelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.sel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel([NotNull] AScriptParser.SelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.gp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGp([NotNull] AScriptParser.GpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.gp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGp([NotNull] AScriptParser.GpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.eos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEos([NotNull] AScriptParser.EosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.eos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEos([NotNull] AScriptParser.EosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dataframe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataframe([NotNull] AScriptParser.DataframeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dataframe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataframe([NotNull] AScriptParser.DataframeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.flt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlt([NotNull] AScriptParser.FltContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.flt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlt([NotNull] AScriptParser.FltContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] AScriptParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] AScriptParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.todata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTodata([NotNull] AScriptParser.TodataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.todata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTodata([NotNull] AScriptParser.TodataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dataitem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataitem([NotNull] AScriptParser.DataitemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dataitem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataitem([NotNull] AScriptParser.DataitemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.load"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad([NotNull] AScriptParser.LoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.load"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad([NotNull] AScriptParser.LoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.export"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExport([NotNull] AScriptParser.ExportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.export"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExport([NotNull] AScriptParser.ExportContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.sort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSort([NotNull] AScriptParser.SortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.sort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSort([NotNull] AScriptParser.SortContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDist([NotNull] AScriptParser.DistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDist([NotNull] AScriptParser.DistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.isall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsall([NotNull] AScriptParser.IsallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.isall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsall([NotNull] AScriptParser.IsallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.limit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimit([NotNull] AScriptParser.LimitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.limit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimit([NotNull] AScriptParser.LimitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.intersect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntersect([NotNull] AScriptParser.IntersectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.intersect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntersect([NotNull] AScriptParser.IntersectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.except"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExcept([NotNull] AScriptParser.ExceptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.except"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExcept([NotNull] AScriptParser.ExceptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.union"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnion([NotNull] AScriptParser.UnionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.union"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnion([NotNull] AScriptParser.UnionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop([NotNull] AScriptParser.DropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop([NotNull] AScriptParser.DropContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.newcase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewcase([NotNull] AScriptParser.NewcaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.newcase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewcase([NotNull] AScriptParser.NewcaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joincase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoincase([NotNull] AScriptParser.JoincaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joincase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoincase([NotNull] AScriptParser.JoincaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.multicase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulticase([NotNull] AScriptParser.MulticaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.multicase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulticase([NotNull] AScriptParser.MulticaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.multiwhen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiwhen([NotNull] AScriptParser.MultiwhenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.multiwhen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiwhen([NotNull] AScriptParser.MultiwhenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.newcolumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewcolumn([NotNull] AScriptParser.NewcolumnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.newcolumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewcolumn([NotNull] AScriptParser.NewcolumnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.context"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContext([NotNull] AScriptParser.ContextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.context"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContext([NotNull] AScriptParser.ContextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.conlit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConlit([NotNull] AScriptParser.ConlitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.conlit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConlit([NotNull] AScriptParser.ConlitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.concatstate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatstate([NotNull] AScriptParser.ConcatstateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.concatstate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatstate([NotNull] AScriptParser.ConcatstateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.concatcolumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatcolumn([NotNull] AScriptParser.ConcatcolumnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.concatcolumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatcolumn([NotNull] AScriptParser.ConcatcolumnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.withcolumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithcolumn([NotNull] AScriptParser.WithcolumnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.withcolumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithcolumn([NotNull] AScriptParser.WithcolumnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] AScriptParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] AScriptParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.cube"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCube([NotNull] AScriptParser.CubeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.cube"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCube([NotNull] AScriptParser.CubeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.rollup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRollup([NotNull] AScriptParser.RollupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.rollup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRollup([NotNull] AScriptParser.RollupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.select"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect([NotNull] AScriptParser.SelectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.select"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect([NotNull] AScriptParser.SelectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.groupby"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupby([NotNull] AScriptParser.GroupbyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.groupby"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupby([NotNull] AScriptParser.GroupbyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.filtercondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFiltercondition([NotNull] AScriptParser.FilterconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.filtercondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFiltercondition([NotNull] AScriptParser.FilterconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.sortstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortstatement([NotNull] AScriptParser.SortstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.sortstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortstatement([NotNull] AScriptParser.SortstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.join"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin([NotNull] AScriptParser.JoinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.join"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin([NotNull] AScriptParser.JoinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.multijoin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultijoin([NotNull] AScriptParser.MultijoinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.multijoin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultijoin([NotNull] AScriptParser.MultijoinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation([NotNull] AScriptParser.RelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation([NotNull] AScriptParser.RelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.aggtype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggtype([NotNull] AScriptParser.AggtypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.aggtype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggtype([NotNull] AScriptParser.AggtypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joindata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoindata([NotNull] AScriptParser.JoindataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joindata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoindata([NotNull] AScriptParser.JoindataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joinfield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinfield([NotNull] AScriptParser.JoinfieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joinfield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinfield([NotNull] AScriptParser.JoinfieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joinedfield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedfield([NotNull] AScriptParser.JoinedfieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joinedfield"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedfield([NotNull] AScriptParser.JoinedfieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joineddata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoineddata([NotNull] AScriptParser.JoineddataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joineddata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoineddata([NotNull] AScriptParser.JoineddataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare([NotNull] AScriptParser.DeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare([NotNull] AScriptParser.DeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.datafields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatafields([NotNull] AScriptParser.DatafieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.datafields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatafields([NotNull] AScriptParser.DatafieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder([NotNull] AScriptParser.OrderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder([NotNull] AScriptParser.OrderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] AScriptParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] AScriptParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.agg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgg([NotNull] AScriptParser.AggContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.agg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgg([NotNull] AScriptParser.AggContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.selectsort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectsort([NotNull] AScriptParser.SelectsortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.selectsort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectsort([NotNull] AScriptParser.SelectsortContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.limitvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimitvalue([NotNull] AScriptParser.LimitvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.limitvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimitvalue([NotNull] AScriptParser.LimitvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchema([NotNull] AScriptParser.SchemaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchema([NotNull] AScriptParser.SchemaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.schemaname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchemaname([NotNull] AScriptParser.SchemanameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.schemaname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchemaname([NotNull] AScriptParser.SchemanameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
