//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AScript.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IAScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] AScriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] AScriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] AScriptParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] AScriptParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] AScriptParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] AScriptParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrfield([NotNull] AScriptParser.StrfieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrfield([NotNull] AScriptParser.StrfieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrvalue([NotNull] AScriptParser.StrvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrvalue([NotNull] AScriptParser.StrvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strreplacevalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrreplacevalue([NotNull] AScriptParser.StrreplacevalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strreplacevalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrreplacevalue([NotNull] AScriptParser.StrreplacevalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDr([NotNull] AScriptParser.DrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDr([NotNull] AScriptParser.DrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.ns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNs([NotNull] AScriptParser.NsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.ns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNs([NotNull] AScriptParser.NsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.nsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNsp([NotNull] AScriptParser.NspContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.nsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNsp([NotNull] AScriptParser.NspContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.imptext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImptext([NotNull] AScriptParser.ImptextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.imptext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImptext([NotNull] AScriptParser.ImptextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.imp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImp([NotNull] AScriptParser.ImpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.imp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImp([NotNull] AScriptParser.ImpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.nullreplace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullreplace([NotNull] AScriptParser.NullreplaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.nullreplace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullreplace([NotNull] AScriptParser.NullreplaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringreplace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringreplace([NotNull] AScriptParser.StringreplaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringreplace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringreplace([NotNull] AScriptParser.StringreplaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.nadrop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNadrop([NotNull] AScriptParser.NadropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.nadrop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNadrop([NotNull] AScriptParser.NadropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData([NotNull] AScriptParser.DataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData([NotNull] AScriptParser.DataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dataformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataformat([NotNull] AScriptParser.DataformatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dataformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataformat([NotNull] AScriptParser.DataformatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.comparedate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparedate([NotNull] AScriptParser.ComparedateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.comparedate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparedate([NotNull] AScriptParser.ComparedateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.adddate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdddate([NotNull] AScriptParser.AdddateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.adddate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdddate([NotNull] AScriptParser.AdddateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.datediff"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatediff([NotNull] AScriptParser.DatediffContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.datediff"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatediff([NotNull] AScriptParser.DatediffContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.monthadd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonthadd([NotNull] AScriptParser.MonthaddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.monthadd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonthadd([NotNull] AScriptParser.MonthaddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.monthbetween"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonthbetween([NotNull] AScriptParser.MonthbetweenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.monthbetween"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonthbetween([NotNull] AScriptParser.MonthbetweenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.next"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNext([NotNull] AScriptParser.NextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.next"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNext([NotNull] AScriptParser.NextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.formatingstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatingstring([NotNull] AScriptParser.FormatingstringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.formatingstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatingstring([NotNull] AScriptParser.FormatingstringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.todate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTodate([NotNull] AScriptParser.TodateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.todate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTodate([NotNull] AScriptParser.TodateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.totime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTotime([NotNull] AScriptParser.TotimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.totime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTotime([NotNull] AScriptParser.TotimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dateformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDateformat([NotNull] AScriptParser.DateformatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dateformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDateformat([NotNull] AScriptParser.DateformatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.datefunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatefunction([NotNull] AScriptParser.DatefunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.datefunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatefunction([NotNull] AScriptParser.DatefunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dateadvancefunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDateadvancefunction([NotNull] AScriptParser.DateadvancefunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dateadvancefunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDateadvancefunction([NotNull] AScriptParser.DateadvancefunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringfunction([NotNull] AScriptParser.StringfunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringfunction([NotNull] AScriptParser.StringfunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringformat([NotNull] AScriptParser.StringformatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringformat([NotNull] AScriptParser.StringformatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.numberfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberfunction([NotNull] AScriptParser.NumberfunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.numberfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberfunction([NotNull] AScriptParser.NumberfunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.numberformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberformat([NotNull] AScriptParser.NumberformatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.numberformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberformat([NotNull] AScriptParser.NumberformatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.strings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrings([NotNull] AScriptParser.StringsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.strings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrings([NotNull] AScriptParser.StringsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.stringltr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringltr([NotNull] AScriptParser.StringltrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.stringltr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringltr([NotNull] AScriptParser.StringltrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFields([NotNull] AScriptParser.FieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFields([NotNull] AScriptParser.FieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSel([NotNull] AScriptParser.SelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSel([NotNull] AScriptParser.SelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.gp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGp([NotNull] AScriptParser.GpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.gp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGp([NotNull] AScriptParser.GpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEos([NotNull] AScriptParser.EosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEos([NotNull] AScriptParser.EosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dataframe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataframe([NotNull] AScriptParser.DataframeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dataframe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataframe([NotNull] AScriptParser.DataframeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.flt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlt([NotNull] AScriptParser.FltContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.flt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlt([NotNull] AScriptParser.FltContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] AScriptParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] AScriptParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.todata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTodata([NotNull] AScriptParser.TodataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.todata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTodata([NotNull] AScriptParser.TodataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dataitem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataitem([NotNull] AScriptParser.DataitemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dataitem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataitem([NotNull] AScriptParser.DataitemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.load"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoad([NotNull] AScriptParser.LoadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.load"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoad([NotNull] AScriptParser.LoadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.export"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExport([NotNull] AScriptParser.ExportContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.export"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExport([NotNull] AScriptParser.ExportContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.sort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSort([NotNull] AScriptParser.SortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.sort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSort([NotNull] AScriptParser.SortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.dist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDist([NotNull] AScriptParser.DistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.dist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDist([NotNull] AScriptParser.DistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.isall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsall([NotNull] AScriptParser.IsallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.isall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsall([NotNull] AScriptParser.IsallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.limit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimit([NotNull] AScriptParser.LimitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.limit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimit([NotNull] AScriptParser.LimitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.intersect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntersect([NotNull] AScriptParser.IntersectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.intersect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntersect([NotNull] AScriptParser.IntersectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.except"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExcept([NotNull] AScriptParser.ExceptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.except"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExcept([NotNull] AScriptParser.ExceptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion([NotNull] AScriptParser.UnionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion([NotNull] AScriptParser.UnionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop([NotNull] AScriptParser.DropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop([NotNull] AScriptParser.DropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.newcase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewcase([NotNull] AScriptParser.NewcaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.newcase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewcase([NotNull] AScriptParser.NewcaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joincase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoincase([NotNull] AScriptParser.JoincaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joincase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoincase([NotNull] AScriptParser.JoincaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.multicase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulticase([NotNull] AScriptParser.MulticaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.multicase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulticase([NotNull] AScriptParser.MulticaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.multiwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiwhen([NotNull] AScriptParser.MultiwhenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.multiwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiwhen([NotNull] AScriptParser.MultiwhenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.newcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewcolumn([NotNull] AScriptParser.NewcolumnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.newcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewcolumn([NotNull] AScriptParser.NewcolumnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.context"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContext([NotNull] AScriptParser.ContextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.context"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContext([NotNull] AScriptParser.ContextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.conlit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConlit([NotNull] AScriptParser.ConlitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.conlit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConlit([NotNull] AScriptParser.ConlitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.concatstate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatstate([NotNull] AScriptParser.ConcatstateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.concatstate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatstate([NotNull] AScriptParser.ConcatstateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.concatcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatcolumn([NotNull] AScriptParser.ConcatcolumnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.concatcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatcolumn([NotNull] AScriptParser.ConcatcolumnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.withcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithcolumn([NotNull] AScriptParser.WithcolumnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.withcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithcolumn([NotNull] AScriptParser.WithcolumnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] AScriptParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] AScriptParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.cube"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCube([NotNull] AScriptParser.CubeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.cube"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCube([NotNull] AScriptParser.CubeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.rollup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRollup([NotNull] AScriptParser.RollupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.rollup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRollup([NotNull] AScriptParser.RollupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect([NotNull] AScriptParser.SelectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect([NotNull] AScriptParser.SelectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.groupby"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupby([NotNull] AScriptParser.GroupbyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.groupby"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupby([NotNull] AScriptParser.GroupbyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.filtercondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFiltercondition([NotNull] AScriptParser.FilterconditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.filtercondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFiltercondition([NotNull] AScriptParser.FilterconditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.sortstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortstatement([NotNull] AScriptParser.SortstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.sortstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortstatement([NotNull] AScriptParser.SortstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoin([NotNull] AScriptParser.JoinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoin([NotNull] AScriptParser.JoinContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.multijoin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultijoin([NotNull] AScriptParser.MultijoinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.multijoin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultijoin([NotNull] AScriptParser.MultijoinContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelation([NotNull] AScriptParser.RelationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelation([NotNull] AScriptParser.RelationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.aggtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggtype([NotNull] AScriptParser.AggtypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.aggtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggtype([NotNull] AScriptParser.AggtypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joindata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoindata([NotNull] AScriptParser.JoindataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joindata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoindata([NotNull] AScriptParser.JoindataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joinfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinfield([NotNull] AScriptParser.JoinfieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joinfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinfield([NotNull] AScriptParser.JoinfieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joinedfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinedfield([NotNull] AScriptParser.JoinedfieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joinedfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinedfield([NotNull] AScriptParser.JoinedfieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.joineddata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoineddata([NotNull] AScriptParser.JoineddataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.joineddata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoineddata([NotNull] AScriptParser.JoineddataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare([NotNull] AScriptParser.DeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare([NotNull] AScriptParser.DeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.datafields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatafields([NotNull] AScriptParser.DatafieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.datafields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatafields([NotNull] AScriptParser.DatafieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrder([NotNull] AScriptParser.OrderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrder([NotNull] AScriptParser.OrderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] AScriptParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] AScriptParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.agg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgg([NotNull] AScriptParser.AggContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.agg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgg([NotNull] AScriptParser.AggContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.selectsort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectsort([NotNull] AScriptParser.SelectsortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.selectsort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectsort([NotNull] AScriptParser.SelectsortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.limitvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimitvalue([NotNull] AScriptParser.LimitvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.limitvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimitvalue([NotNull] AScriptParser.LimitvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchema([NotNull] AScriptParser.SchemaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchema([NotNull] AScriptParser.SchemaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AScriptParser.schemaname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchemaname([NotNull] AScriptParser.SchemanameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AScriptParser.schemaname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchemaname([NotNull] AScriptParser.SchemanameContext context);
}
