//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AScript.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IAScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] AScriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] AScriptParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] AScriptParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.strfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrfield([NotNull] AScriptParser.StrfieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.strvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrvalue([NotNull] AScriptParser.StrvalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.strreplacevalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrreplacevalue([NotNull] AScriptParser.StrreplacevalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDr([NotNull] AScriptParser.DrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.ns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNs([NotNull] AScriptParser.NsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.nsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNsp([NotNull] AScriptParser.NspContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.imptext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImptext([NotNull] AScriptParser.ImptextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.imp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImp([NotNull] AScriptParser.ImpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.nullreplace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullreplace([NotNull] AScriptParser.NullreplaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.stringreplace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringreplace([NotNull] AScriptParser.StringreplaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.nadrop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNadrop([NotNull] AScriptParser.NadropContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData([NotNull] AScriptParser.DataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dataformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataformat([NotNull] AScriptParser.DataformatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.comparedate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparedate([NotNull] AScriptParser.ComparedateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.adddate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdddate([NotNull] AScriptParser.AdddateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.datediff"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatediff([NotNull] AScriptParser.DatediffContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.monthadd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthadd([NotNull] AScriptParser.MonthaddContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.monthbetween"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthbetween([NotNull] AScriptParser.MonthbetweenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.next"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNext([NotNull] AScriptParser.NextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.formatingstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormatingstring([NotNull] AScriptParser.FormatingstringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.todate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTodate([NotNull] AScriptParser.TodateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.totime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotime([NotNull] AScriptParser.TotimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dateformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateformat([NotNull] AScriptParser.DateformatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.datefunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatefunction([NotNull] AScriptParser.DatefunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dateadvancefunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateadvancefunction([NotNull] AScriptParser.DateadvancefunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.stringfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringfunction([NotNull] AScriptParser.StringfunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.stringformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringformat([NotNull] AScriptParser.StringformatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.numberfunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberfunction([NotNull] AScriptParser.NumberfunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.numberformat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberformat([NotNull] AScriptParser.NumberformatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.strings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrings([NotNull] AScriptParser.StringsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.stringltr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringltr([NotNull] AScriptParser.StringltrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields([NotNull] AScriptParser.FieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSel([NotNull] AScriptParser.SelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.gp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGp([NotNull] AScriptParser.GpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEos([NotNull] AScriptParser.EosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dataframe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataframe([NotNull] AScriptParser.DataframeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.flt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlt([NotNull] AScriptParser.FltContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] AScriptParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.todata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTodata([NotNull] AScriptParser.TodataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dataitem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataitem([NotNull] AScriptParser.DataitemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.load"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoad([NotNull] AScriptParser.LoadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.export"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExport([NotNull] AScriptParser.ExportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.sort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort([NotNull] AScriptParser.SortContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.dist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDist([NotNull] AScriptParser.DistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.isall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsall([NotNull] AScriptParser.IsallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.limit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit([NotNull] AScriptParser.LimitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.intersect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntersect([NotNull] AScriptParser.IntersectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.except"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExcept([NotNull] AScriptParser.ExceptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion([NotNull] AScriptParser.UnionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop([NotNull] AScriptParser.DropContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.newcase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewcase([NotNull] AScriptParser.NewcaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.joincase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoincase([NotNull] AScriptParser.JoincaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.multicase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulticase([NotNull] AScriptParser.MulticaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.multiwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiwhen([NotNull] AScriptParser.MultiwhenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.newcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewcolumn([NotNull] AScriptParser.NewcolumnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.context"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext([NotNull] AScriptParser.ContextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.conlit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConlit([NotNull] AScriptParser.ConlitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.concatstate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatstate([NotNull] AScriptParser.ConcatstateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.concatcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatcolumn([NotNull] AScriptParser.ConcatcolumnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.withcolumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWithcolumn([NotNull] AScriptParser.WithcolumnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] AScriptParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.cube"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCube([NotNull] AScriptParser.CubeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.rollup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRollup([NotNull] AScriptParser.RollupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect([NotNull] AScriptParser.SelectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.groupby"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupby([NotNull] AScriptParser.GroupbyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.filtercondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFiltercondition([NotNull] AScriptParser.FilterconditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.sortstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortstatement([NotNull] AScriptParser.SortstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin([NotNull] AScriptParser.JoinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.multijoin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultijoin([NotNull] AScriptParser.MultijoinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelation([NotNull] AScriptParser.RelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.aggtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggtype([NotNull] AScriptParser.AggtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.joindata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoindata([NotNull] AScriptParser.JoindataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.joinfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinfield([NotNull] AScriptParser.JoinfieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.joinedfield"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoinedfield([NotNull] AScriptParser.JoinedfieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.joineddata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoineddata([NotNull] AScriptParser.JoineddataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare([NotNull] AScriptParser.DeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.datafields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatafields([NotNull] AScriptParser.DatafieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder([NotNull] AScriptParser.OrderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] AScriptParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.agg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgg([NotNull] AScriptParser.AggContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.selectsort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectsort([NotNull] AScriptParser.SelectsortContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.limitvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimitvalue([NotNull] AScriptParser.LimitvalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchema([NotNull] AScriptParser.SchemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AScriptParser.schemaname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchemaname([NotNull] AScriptParser.SchemanameContext context);
}
